### ISSUE TITLE
Amazon Login Captcha

### ISSUE THREAD

**Issue by Dreadis-darkore** [Hari-Nagarajan/fairgame#396]
**Describe the bug**
When moving through the login portion of startup on Amazon a simple text Captcha is appearing. When Fairgame then tries to go to the product page it gets sent to an Amazon error page.

**To Reproduce**
1 (assumed) trigger some form of amazon internal bot protection
2 Fail to solve or stop for user to solve captcha when it appears

**Expected behavior**
to not fail ofcourse

**Screenshots**
https://imgur.com/a/JoBcDHS (screenshot from the login process)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser Chrome
 - Version 87.0.4280.88 (Official Build) (64-bit) (cohort: Stable)

**Additional context**
Only started having the problem after many hours (8-12+) of usage of the bot. Even a simple hit enter to continue on the command line at login would let me take the time to solve the captcha.

**Comment by worst-mod-confirmed** [comment]
whats your amazon_website: line look like in the config

**Comment by DakkJaniels** [comment]
What did terminal say? Did it recognize it was on captcha?

**Comment by Dreadis-darkore** [comment]
"amazon_website": "www.amazon.com"

It didn't recognize that there was a captcha at all. it just tried to load the product page for the processor i wanted and repeatedly got the amazon error page instead.

**Comment by worst-mod-confirmed** [comment]
change that to smile.amazon.com and select a charity that has some meaning to you and it should fix your issue.

**Comment by Dreadis-darkore** [comment]
Ah ok. I'll do that once i set a new target for it. I managed to get lucky with a manual purchase.

**Comment by omnomonous** [comment]
was this figured out? smile.amazon.com still not passing captcha

**Comment by DakkJaniels** [comment]
The original issue was that the bot didn't recognized there was a captcha. As far as I am aware, that issue has been resolved. For solving the captcha, we are using the amazoncaptcha module, so if that can't solve it, then we can't do anything about it.

At the moment, the pipfile set the amazoncaptcha version to `"==0.4.4"`. If you want to try changing that to `"*"` and rerun `pipenv install`, maybe the latest version will pass captchas a little better. The next FairGame release (no ETA) will include that change, and also enable logging for captchas that could not be solved.

**Comment by robocorpse** [comment]
I am also getting stuck on captcha

**Comment by WeeFergus** [comment]
Tried reinstalling pipenv with the amazoncaptcha set to "*".  No dice. Still hangs on captcha.

**Comment by shroyhammer** [comment]
I too have this problem on all repositories running at multiple locations.
I have to manually pass these captchas, and then the scripts run unabated for a period of hours and then I am tested again by this no dick nonsense.
This malfunction costed me yesterday when the 3080's dropped on amazon and both of my set ups were stuck at the captcha screen.  After over a month of keeping these things running, the first real chance I had at a win was RUINED by CAPTCHAS.
WTF mate. This is how I feel now:
 https://www.youtube.com/watch?v=Rt4rzRCy_XU

in other news, thanks again for making fair game. Despite its flaws, insert "so you're telling me there's a chance" .gif.

**Comment by Dhogan778** [comment]
same randomly happens

**Comment by shroyhammer** [comment]
![CAPTCHA error](https://user-images.githubusercontent.com/79087957/111831909-439cc780-88ad-11eb-8f4b-8efc1e666cf5.png)
here's a screenie of this nightmare

**Comment by gtrak** [comment]
Let's be real, you probably weren't getting those 3080s :D. Mine doesn't
suffer from the captchas and didn't even see them.

**Comment by shroyhammer** [comment]
@gtrak YAY! I GOT ONE!

**Comment by DakkJaniels** [comment]
@shroyhammer what did you get?

**Comment by mechjoer** [comment]
It I didn’t get it. Didn’t check it out

Sent from my iPhone
2017251356

**Comment by Nagorak** [comment]
I also had this problem today. The program didn't even recognize there was a CAPTCHA and I was forced to try to intervene, but by then it was too late. Maybe wouldn't have gotten it anyway, but it actually managed to add a 3060 to cart, so kind of a bummer not to find out.

**Comment by adfayed** [comment]
I am getting the same issue. The chrome instance that is running blocks all images. is that perhaps the problem? The chrome instance won't allow me to allow images. Is there a way to do that through cmd line args?

**Comment by RealPwned** [comment]
same issue since yesterday... the bot solves the captcha, but it takes up to 15 seconds :/

![image](https://user-images.githubusercontent.com/44307473/114954154-33e7b300-9e5a-11eb-9f0f-32c86c16fd98.png)

![image](https://user-images.githubusercontent.com/44307473/114954278-7a3d1200-9e5a-11eb-830d-04311ef380f4.png)
